server:
  servlet:
    context-path: /authentication
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/authentication
    username: admin
    password: admin
    jpa:
      hibernate:
        ddl-auto: none
      properties:
        hibernate:
          default_schema: authentication
      show-sql: true
      database: authentication
      generate-sql: false
      open-in-view: false
  flyway:
    url: jdbc:postgresql://localhost:5432/authentication
    user: admin
    password: admin
    schemas:
      - authentication
    baseline-on-migrate: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher