server:
  servlet:
    context-path: /authentication
  port: ${PORT:8080}

cryptography:
  secret-key: ${SECRETKEY}
  salt: ${SALT}

spring:
  cloud:
    aws:
      endpoint: ${AWS_ENDPOINT}
      credentials:
        access-key: ${ACCESS_KEY}
        secret-key: ${SECRET_KEY}
      sns:
        endpoint: ${AWS_SNS_ENDPOINT}
        authentication-user-domain-event: ${AUTHENTICATION_USER_DOMAIN_EVENT}
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: ${DB_SCHEMA}
    show-sql: true
    database: postgresql
    generate-sql: false
    open-in-view: false
  flyway:
    enabled: false
    baseline-on-migrate: true
    schemas:
      - ${DB_SCHEMA}
    create-schemas: true

security:
  token:
    issuer: ${ISSUER}
    publicKey: ${PUBLICKEY}
    privateKey: ${PRIVATEKEY}
    maxAgeSeconds: ${MAXAGESECONDS}