server:
  servlet:
    context-path: /authentication
  port: ${PORT:8080}

cryptography:
  secret-key: ${SECRETKEY}
  salt: ${SALT}

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: ${DB_SCHEMA}
    show-sql: true
    database: postgresql
    generate-sql: false
    open-in-view: false

security:
  token:
    issuer: ${ISSUER}
    publicKey: ${PUBLICKEY}
    privateKey: ${PRIVATEKEY}
    maxAgeSeconds: ${MAXAGESECONDS}