CREATE TABLE IF NOT EXISTS authentication.role(
    ID INT NOT NULL,
    NAME VARCHAR(35) NOT NULL,
    DESCRIPTION VARCHAR(60),
    PRIMARY KEY(ID)
);

CREATE SEQUENCE authentication.SQ_ROLE
    START 1
    INCREMENT 1;

ALTER TABLE authentication.user ADD ROLE_ID INT NOT NULL;

ALTER TABLE authentication.user ADD CONSTRAINT fk_user_role FOREIGN KEY (role_id) REFERENCES authentication.role(id);
--
-- CREATE TABLE IF NOT EXISTS AUTHENTICATION.USER_ROLE(
--     ROLE_ID INT NOT NULL,
--     USER_ID INT NOT NULL,
--     PRIMARY KEY(ROLE_ID, USER_ID),
--
--     CONSTRAINT FK_USER_ROLE FOREIGN KEY(ROLE_ID) REFERENCES AUTHENTICATION.USER(ID),
--     CONSTRAINT FK_ROLE_USER FOREIGN KEY(USER_ID) REFERENCES AUTHENTICATION.ROLE(ID)
);
